config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
  	resources :reviews
  end
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :reviews

	 has_attached_file :book_img, styles: { :book_index => "250x360>", :book_show => "325x375>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :book
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		if params[:category].blank?
			@books = Book.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		if @book.reviews.blank?
			@average_review = 0
		else
			@average_review = @book.reviews.average(:rating).round(2)
		end
	end

	def new

		@book = current_user.books.build
		@categories = Category.all.map{|c| [c.name, c.id]}
	end

	def create
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]

		if @book.save
		 	redirect_to root_path
		 else
		 	@categories = Category.all.map{ |c| [c.name, c.id]}
		 	render 'new'
		 end


	end
	def edit
		@categories = Category.all.map{ |c| [c.name, c.id]}

	end

	def update
		@book.category_id = params[:category_id]
		
		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'edit'

		end

	end

	def destroy
		@book.destroy
		redirect_to root_path
	end

	private 
		def book_params
		params.require(:book).permit(:title, :description, :author, :category_id, :book_img)

	end

	def find_book
		@book = Book.find(params[:id])
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]
	

	def new
		@review = Review.new
	end


	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
	end
  end

  def edit
  	@review = Review.find(params[:id])

  end

  def update
  	 	
  	 	if @review.update(review_params)
  	 		redirect_to book_path(@book)
  	 	else
  	 		render 'edit'
  	 	end
  end
  	def destroy
  		@review.destroy
  		redirect_to book_path(@book)
  	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
	end

	def find_book
		@book = Book.find(params[:book_id])
	end

	def find_review
		@review = Review.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => {:multipat => true } do |f| %>


  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>

  
  <%= f.file_field :book_img %>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :description%>
  <%= f.input :author %>
  <%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	
	<div class="edit-book-form">
		

	<h1>Edit Book</h1>

	<%= simple_form_for @book, :html => {:multipat => true } do |f| %>
	  <%= f.select :category_id, @categories %>
	  <%= f.file_field :book_img %>
	  <%= f.input :title, label: "Book Title" %>
	  <%= f.input :description%>
	  <%= f.input :author %>
	  <%= f.button :submit, class: "btn-custom2" %>
	<% end %>
</div>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>
	<h1>There are no books in this category</h1>

<% else %>

	<div class="row">
		
	<% @books.each do |book| %>

			<div class="col-md-3">
				<a href="/books/<%= book.id %>">
					<%= image_tag book.book_img.url(:book_index), class: "book" %>
				</a>
 			</div>
	
		<% end %>
	</div>
	
<% end %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">
	
	<div class="new-book-form">
		

		<h1>New Book</h1>

		<%= render 'form' %>
	</div>
</div>

app/views/books/show.html.erb
<div class="row">

<div class="col-md-4">
	<%= image_tag @book.book_img.url(:book_show), class: "book-show" %>

</div>
	
	<div class="col-md-8">
		<div class="book-info">
			<h2 class="book-title"><%= @book.title %></h2>
			<h2 class="book-author"><span> From </span><%= @book.author %></h2>
			<h2 class="averageirating">Average Rating</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews">Based on <%= @book.reviews.count %> reviews</span>

			<p class="book-desc"><%= @book.description %></p>
		</div>

	</div>
	</div>

</div>

<div class="row">
	<div class="col-md-4">

	<div class="reviews">


	<!-- This is were the review/ratings will go -->
		<h1>Reviews</h1>
		<%= render @book.reviews %>

		<div>
		<%= link_to "Add Review", new_book_review_path(@book), class: "btn-custom" %>
		</div>
	</div>
		
	</div>
	
</div>


	<div class="links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>

		<% if user_signed_in? %>

	<% if @book.user_id == current_user.id %>

		<%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom" %>
		<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you Sure?"}, class: "btn btn-custom" %>


	
	<% end %>
<% end %>

</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets'
	})

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">

  	<div class="container">

  		<div class="navbar-header">
  		<%= link_to "Book Review", root_path, class: "navbar-brand" %>
  			
  		</div>

  		<ul class="nav navbar-nav">
  			<li><%= link_to "Sign Up", new_user_registration_path %></li>

  				<% if user_signed_in? %>
  					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>

  				<% else %>
  					<li><%= link_to "Log In", new_user_session_path %></li>
  				<% end %>
  		</ul>

  		<ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if params[:category] == category.name %>">
                  <%= link_to category.name, books_path(category: category.name), class: "link" %>
                </li>
              <% end %>
            </ul>
          
        </li>

   			<% if user_signed_in? %>

  				<li><%= link_to "Add Book", new_book_path %></li>


  		<% end %>
  			
  		</ul>
  		
  	</div>
  	
  </nav>

   
     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
    </div>
  


  </body>
</html>

app/views/reviews/_form.html.erb
	<div class="col-md-6 col-md-offset-3">
		
		<div class="signup-form">
			


		<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
			<div id="rating-form">
				

			<label>Rating</label>
				</div>

			<%= f.input :comment %>
			<%= f.button :submit, class: "btn-custom2" %>
		<% end %>
	</div>
</div>

<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
	
</script>

app/views/reviews/_review.html.erb
<div class="review">

<div class="review-rating" data-score="<%= review.rating %>"></div> 
<p class="review-comment"><%= review.comment %></p>

<% if user_signed_in? %>

	<% if review.user_id == current_user.id %>

	<div class="links btn-group">

	<%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom"  %>
	<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: {
	confirm: "Are you sure?"}, class: "btn btn-custom"  %>

	</div>
 <% end %>
<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	
	<div class="new-review-form">
		

		<h1>Edit Review</h1>
		<%= simple_form_for([@book, @review]) do |f| %>
			
			<div id="rating-form">
				

			<label>Rating</label>
				</div>
				
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>
	</div>
</div>


<script>
$('#rating-form').raty({
	path: '/assets/',
	scoreName: 'review[rating]'
});
	
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
	
	<div class="new-review-form">
		

		<h1>New Review</h1>

		<%= render 'form' %>
	</div>
</div>